name: Docker Image CI pdns-mysql fedora

on:
  push:
    tags:
      - 'pdns-mysql-fedora-*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set output
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF##*-}

      - name: Build and push PDNS
        id: docker_build_pdns
        uses: docker/build-push-action@v2
        with:
          context: ./pdns
          file: ./pdns/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pdns-mysql:${{ steps.vars.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker_build_pdns.outputs.digest }}
