name: Docker Image CI for PRs

on:
  pull_request:
    branches: [ master ]

jobs:

  test-recursor-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build PDNS Recursor latest
        id: docker_build_recursor_latest
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-recursor
          file: ./pdns-recursor/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: pdns-recursor:latest
      - name: Image digest
        run: echo ${{ steps.docker_build_recursor_latest.outputs.digest }}

  test-recursor-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build PDNS Recursor alpine
        id: docker_build_recursor_alpine
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-recursor
          file: ./pdns-recursor/Dockerfile.alpine
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: pdns-recursor:alpine
      - name: Image digest
        run: echo ${{ steps.docker_build_recursor_alpine.outputs.digest }}

  test-pdns-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build PDNS latest
        id: docker_build_pdns_latest
        uses: docker/build-push-action@v5
        with:
          context: ./pdns
          file: ./pdns/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: pdns-mysql:latest
      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_latest.outputs.digest }}

  test-pdns-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build PDNS alpine
        id: docker_build_pdns_alpine
        uses: docker/build-push-action@v5
        with:
          context: ./pdns
          file: ./pdns/Dockerfile.alpine
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: pdns-mysql:alpine
      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_alpine.outputs.digest }}

  test-pdns-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build pdns admin
        id: docker_build_pdns_admin
        uses: docker/build-push-action@v5
        with:
          context: ./pdns-admin
          file: ./pdns-admin/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: |
            pdns-admin:latest
      - name: Image digest
        run: echo ${{ steps.docker_build_pdns_admin.outputs.digest }}
